### ISSUE TITLE
最新大麦抢票助手 五月天已成功上车！！！ 原github地址：https://github.com/ClassmateLin/dm-ticket， MIT协议

### ISSUE THREAD

**Issue by huchuansai** [RookieTree/DaMaiHelper#10]
<img width="759" alt="image" src="https://github.com/RookieTree/DaMaiHelper/assets/50079978/26d8c346-746c-4849-9524-beedb69d01e5">
<img width="823" alt="image" src="https://github.com/RookieTree/DaMaiHelper/assets/50079978/842e3676-2fc5-43de-9fe2-ec411a76979e">

**Comment by Vantiboolean** [comment]
你这种废物，人家开源的你在这钓鱼

原作者
https://github.com/ClassmateLin/dm-ticket

**Comment by AuroraYolo** [comment]
已经都用不了了

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github
