### ISSUE TITLE
看起来不错，尽管我错过了五月天hh

### ISSUE THREAD

**Issue by puryhuang** [RookieTree/DaMaiHelper#13]

**Comment by Abindhs** [comment]
哈哈哈哈哈哈哈哈哈  有其他办法吗 老哥

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮
