### ISSUE TITLE
很厉害，我看错了刚才

### ISSUE THREAD

**Issue by 1562592475** [RookieTree/DaMaiHelper#15]
如题

**Comment by bio-shun** [comment]
有多厉害呀~好不好用哦~

**Comment by 1562592475** [comment]
> 

亲测抢不到，感觉大麦这个平台也多少沾点问题

**Comment by ysxlmk** [comment]
试过,比手动慢,是大麦做了限制了

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github
