### ISSUE TITLE
想问一下app的工作逻辑

### ISSUE THREAD

**Issue by YG00D** [RookieTree/DaMaiHelper#16]
是不是一直监控页面的"即将开抢"按钮变化,然后就点击呀

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮

**Comment by RookieTree** [comment]
是的 目前无效了
