### ISSUE TITLE
部署or打包

### ISSUE THREAD

**Issue by Walt-like** [RookieTree/DaMaiHelper#25]
这是用java写的？怎么部署或者打包（apk）使用

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github

**Comment by jyk0201** [comment]
这边大麦bp，脚本，代码和猫眼bp可长期提供，有需要的来➕q2814249606，备注github。主打信任不扯皮

**Comment by RookieTree** [comment]
使用github 的ci，配置好 就可以自动化打包发布了
