### ISSUE TITLE
感谢！

### ISSUE THREAD

**Issue by kangaroo1122** [RookieTree/DaMaiHelper#27]
今日抢票重庆五月天到手！6的

**Comment by atom077** [comment]
老哥，你真抢到了吗 666

**Comment by kangaroo1122** [comment]
> 老哥，你真抢到了吗 666

![mmexport1693548185903.jpg](https://github.com/RookieTree/DaMaiHelper/assets/26996304/807484fa-9284-482f-bc41-3daefb597813)

**Comment by kangaroo1122** [comment]
> 老哥，你真抢到了吗 666

网络也很重要，这个只是辅助你点击而已

**Comment by atom077** [comment]
> > 老哥，你真抢到了吗 666
> 
> 网络也很重要，这个只是辅助你点击而已

感谢
