### ISSUE TITLE
UserManager.price和UserManager.day代码里没有用到

### ISSUE THREAD

**Issue by xiaozhihong** [RookieTree/DaMaiHelper#4]
请问下, 到选场次选座位必须得人工选择? 感谢

**Comment by RookieTree** [comment]
之前代码是有那块逻辑的，后面删了，所以要在想看里 预选好场次和价格，这样进页面就会直接加票数进购买页

**Comment by xiaozhihong** [comment]
> 之前代码是有那块逻辑的，后面删了，所以要在想看里 预选好场次和价格，这样进页面就会直接加票数进购买页

感谢回复, 期待成功
